FROM eclipse-temurin:21-jdk
WORKDIR /app
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=docker", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"]
